### ISSUE TITLE
pulsing opacity doesn't work

### ISSUE THREAD

**Issue by yairEO** [jsoverson/jquery.pulse.js#10]
doing this won't do anything:

```
$('.elm').pulse({ opacity:'0.1'}, { duration:1000, pulses:3 });
```

**Comment by jsoverson** [comment]
Works for me, enter `
$('h1').pulse({opacity:.1},{ duration:1000, pulses:3})` in the console at http://jsoverson.github.io/jquery.pulse.js/ on both chrome and firefox

**Comment by yairEO** [comment]
I have a very weird problem where I do:

```
$foo.on('click.vote', 'img', function(){
          $(this).siblings('.bar').pulse({ opacity:.1 },{ duration:1000, pulses:3})
 })
```

and it will **only** pulsate while the mouse is moving on the image. As long as the mouse moves, pulse works. will not do anything while mouse isn't moving (after click of course).

Would you know anything of this? (WIN7, FF32)

Thanks
