### ISSUE TITLE
Can't use pulse with box-shadow

### ISSUE THREAD

**Issue by Err0r404** [jsoverson/jquery.pulse.js#2]
Hi,

I'm trying to use pulse.js with the box-shadow properties but I can't get it working...

Here is an exemple : http://jsfiddle.net/93S2B/

Thanks

**Comment by geilt** [comment]
jQuery animate doesn't support box-shadow if I remember correctly.

You may need to use a plugin to extend that functionality. 

Possible: http://www.bitstorm.org/jquery/shadow-animation/ ?

Yes that worked.

I included http://www.bitstorm.org/jquery/shadow-animation/jquery.animate-shadow.js with the script on your fiddle and the shadows worked.

http://jsfiddle.net/93S2B/1/

**Comment by jsoverson** [comment]
Awesome, thanks for clarifying, @geilt
