### ISSUE TITLE
rapid triggering causes loss of original property

### ISSUE THREAD

**Issue by mikeatlas** [jsoverson/jquery.pulse.js#5]
This can be demonstrated on the demo page itself. Rapidly click on the first red pulse example. The text will end up stuck red eventually as the 'original' color is queued up from it's partially transitioned color.

I ran into this same problem while writing my own pulsing effect animation and was hoping you had worked out queuing animations, which I was struggling to complete in a timely manner for a project I'm working on. 

I believe what needs to be done is that if a control has an effect queue _fx_, and if the animation being queued is the first in an empty queue, the original state of the control must also be stored and always restored when the queue is empty again.

**Comment by r1c4r60** [comment]
@mikeatlas 

Faced the same issue. Please, try in the following modification: It worked for me.

from:

if (el.data('pulse').stop) return;

to:

if (el.data('pulse').stop) {
       el.css(original);
       return;
}

**Comment by pkuzhel** [comment]
this doesn't seem to be a working solution though

**Comment by mikeatlas** [comment]
Well, two years later and I'm not even privy to the code which I was working on at the time regarding this bug, but if I had to approach this again, I'd probably write a function that captured the base state color code, and then use underscore or lo-dash's debounce function plus a done-callback to transition back to the original stored color.

I'm going to close this issue because it's old now and not fixed and I'm not interested in seeing it fixed anymore. Feel free to open a new issue or PR, maybe implement my idea above.
